version: '2'
services: 
  db:
    image: 'postgres:latest'
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  streamlit:
    build:
      context: .
    container_name: "full_stack_news"
    image: "mattfwinans/full_stack_news"
    ports:
      - "8501:8501"

volumes:
  db_data: