apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: streamlit
  name: streamlit
spec:
  replicas: 1
  selector:
    io.kompose.service: streamlit
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: streamlit
    spec:
      containers:
        - image: ' '
          name: full-stack-news
          ports:
            - containerPort: 8501
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - full_stack_news
        from:
          kind: ImageStreamTag
          name: streamlit:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
